### ISSUE TITLE
Manual entry of client credentials rather than list

### ISSUE THREAD

**Issue by seymen** [giteshk/smartdocs_oauth_additions#4]
Hi @giteshk 

I installed this module in a demo portal and configured with client credentials. When I come to generate a token for it, I realised that it is listing all the apps in an org to pick up the relevant client credentials.

However in many situations, developers seeing the list of apps an org has is not desired, i.e. that list is not always public. This also opens up impersonation opportunities for public where a developer who hasn't registered an app can start issuing requests coming from a legitimate app. Apart from all the other security issues, AX and traffic management (e.g. quota per app) will be affected by this. I can easily issue enough requests through smartdocs (automated via Selenium for example) to use up all quota allocations for an app - therefore making the app unusable.

Is there a way to configure the module to either choose some default credentials or populate their client credentials manually instead of picking one from a list? This will force them to register themselves as a developer and prevent them impersonating another app.

Cheers

**Comment by seymen** [comment]
I can see the place where I can put default client credentials in template authentication schemes but I still need a way of disabling list of apps appearing in the dropdown.

**Comment by giteshk** [comment]
@seymen as far as I know it will only show all the apps from the current user. 

There might be an issue with anonymous users but that will need to be verified.
